### ISSUE TITLE
I cant change size of the ng-modal

### ISSUE THREAD

**Issue by XsiSec** [mazdik/ng-modal#12]
I tried to use your example css template but, the ng-modal doesnt change size at all.

please help me out.

**Comment by mazdik** [comment]
try
```css
.modal-demo .ui-modal {
  width: 37.5rem;
  /* for resize limits use min-width, min-height, max-width, max-height in css */
}
```
